### ISSUE TITLE
How to use trained model to predict new image with characters?

### ISSUE THREAD

**Issue by sagarhukkire** [frereit/TensorflowHandwritingRecognition#4]
First thanks for your project. I was wondering since the models are trained on all english characters how I can predict using trained model on new english character image
![name](https://user-images.githubusercontent.com/20017611/39176292-be12f218-47ac-11e8-946a-03d9b3e18247.png)
which will give me out put text as sagar

Thanks

**Comment by frereit** [comment]
This is not possible out of the box. The AI is trained on 32x32 images of single characters, and can only detect one image at a time. If you want to detect whole words, you could use something like opencv to detect the bounding boxes of the characters and then resize them to 32x32. Then predict each character on its own and concatenate the output. You can import predict.py into your own script. You have to modify the predict.py script by renaming the main function to something like predict and let it take an argument of the path to the image. I am currently not at home, but I will give you an example of the modified script later.
________________________________

**Comment by sagarhukkire** [comment]
Ok Thanks I will try too

**Comment by frereit** [comment]
Alright. Won't fix/Add. It will stay at 32x32px single character recognition.
