### ISSUE TITLE
Datasets?

### ISSUE THREAD

**Issue by sagarhukkire** [frereit/TensorflowHandwritingRecognition#5]
Hi,

It is possible for you to share labels and image files(.npy) and trained classifier on NIST files. It will be a great help for me. Currently, I figured out how to get the character out of the word, but CPU is not helping me train on the entire dataset.

Thanks in advance.

Sagar

**Comment by sagarhukkire** [comment]
did it finally

**Comment by garchit33** [comment]
@sagarhukkire can you please tell me how do you segment charcater out of word.
I will be very thankful to you.

**Comment by sagarhukkire** [comment]
Hi

First thing you do is define Region of Intrest for the fields on Forms.
1. ROI contains only handwritten words
2. Apply connected components  (8 or 4) ,  then you will get bounding box
for each character,  crop each one store
5) Train CNN on NIST database, they have million of handwritten characters
images
6) now this CNN apply to your cropped images  ...for every crop character
you will get prediction and you bind them

For example
1. ROI is :  USA
2. Connected components : U, S, A
3) CNN predictions : USA ( after binding )

To improve you can put SVM at last layer of CNN

Hope it will help you
Thanks and Regards
Sagar Hukkire

**Comment by garchit33** [comment]
Do you have any implemented approach of this. Can you please provide me
with the code of this if you have.

Regards
Archit Garg

**Comment by sanksys** [comment]
@sagarhukkire 
hi sagar could you please provide the code (GitRepo link) for comment 6 implementation
mostly for  
2. Apply connected components  (8 or 4) ,  then you will get bounding box
how you approached this ?

thanks 
Sanket
Sankaghav123@gmail.com
